semestralka:
  docker: &semestralka
    - image: 'circleci/python:latest'
      environment:
          ANSIBLE_HOST_KEY_CHECKING: no

version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
           - .
  deploy:
    docker: *semestralka
    steps:
      - attach_workspace:
          at: .
      - run: pip3 install ansible boto boto3
      - run: echo $SSH_PRIVATE_KEY | sed 's/<CRLF>/\n/g' > accessKey.pem
      - run: chmod 400 accessKey.pem
      - run: export ANSIBLE_HOST_KEY_CHECKING=False
      - run: ansible-playbook ansible/ec2_deploy.yml --user ubuntu --key-file accessKey.pem

workflows:
  version: 2.1
  build:
    jobs:
      - build
      - deploy:
         requires:
            - build
         filters:
            branches:
               only: master