version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
           - .ansible
  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - attach_workspace:
          at: .
      - run: pip3 install ansible boto boto3
      - add_ssh_keys:
         fingerprints:
          - "23:25:81:d3:c0:8e:28:7c:0e:0d:c9:00:c0:07:e3:20:3c:34:af:19"
      - run:
         command: ansible-playbook ansible/ec2_deploy.yml --user ubuntu --key-file accesKey.pem
         environment:
            ANSIBLE_HOST_KEY_CHECKING: False
workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
         requires:
            - build
         filters:
            branches:
               only: master